module.exports = class Data1787597049313 {
    name = 'Data1787597049313'

    async up(db) {
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "free" numeric NOT NULL, "reserved" numeric NOT NULL, "frozen" numeric NOT NULL, "nonce" integer NOT NULL, "first_seen_block" integer NOT NULL, "last_active_block" integer NOT NULL, "identity_display" text, "identity_json" jsonb, "identity_status" character varying(10), "identity_sub_name" text, "username" text, "evm_address" text, "vesting_json" jsonb, "locks_json" jsonb, "holds_json" jsonb, "deposits_json" jsonb, "identity_super_id" character varying, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_account_last_active_block_82d33d5a" ON "account" ("last_active_block") `)
        await db.query(`CREATE INDEX "idx_account_identity_display_842c1051" ON "account" ("identity_display") `)
        await db.query(`CREATE INDEX "idx_account_identity_status_8b941a81" ON "account" ("identity_status") `)
        await db.query(`CREATE INDEX "idx_account_identity_super_6eb9fc9a" ON "account" ("identity_super_id") `)
        await db.query(`CREATE INDEX "idx_account_username_e1e37d55" ON "account" ("username") `)
        await db.query(`CREATE INDEX "idx_account_evm_address_66f5172b" ON "account" ("evm_address") `)
        await db.query(`CREATE TABLE "block" ("id" character varying NOT NULL, "height" integer NOT NULL, "hash" text NOT NULL, "parent_hash" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "spec_version" integer NOT NULL, "difficulty" numeric NOT NULL, "reward" numeric NOT NULL, "nonce" text NOT NULL, "work_hash" text NOT NULL, "finalized" boolean NOT NULL, "extrinsic_count" integer NOT NULL, "event_count" integer NOT NULL, "logs" text array NOT NULL, "author_id" character varying, CONSTRAINT "PK_d0925763efb591c2e2ffb267572" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_block_height_b20720ad" ON "block" ("height") `)
        await db.query(`CREATE UNIQUE INDEX "idx_block_hash_b194b635" ON "block" ("hash") `)
        await db.query(`CREATE INDEX "idx_block_timestamp_82806c7c" ON "block" ("timestamp") `)
        await db.query(`CREATE INDEX "idx_block_author_c116954b" ON "block" ("author_id") `)
        await db.query(`CREATE INDEX "idx_block_finalized_b535c2b5" ON "block" ("finalized") `)
        await db.query(`CREATE TABLE "chain_info" ("id" character varying NOT NULL, "name" text NOT NULL, "symbol" text NOT NULL, "decimals" integer NOT NULL, "ss58" integer NOT NULL, "block_time" integer NOT NULL, "existential_deposit" numeric NOT NULL, "evm_chain_id" integer NOT NULL, "session_length" integer NOT NULL, "session_offset" integer NOT NULL, "head" integer NOT NULL, "finalized_head" integer NOT NULL, CONSTRAINT "PK_1b82ce2acbc16bfc7f84bfdc8ff" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "mined_object" ("id" character varying NOT NULL, "protocol" text NOT NULL, "vertices" bytea NOT NULL, "vertex_count" integer NOT NULL, "block_id" character varying, CONSTRAINT "REL_0aea185c9517d8774d2afacfe3" UNIQUE ("block_id"), CONSTRAINT "PK_e33ffff2ccc603f6b29796ab7bb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_mined_object_block_a24f655d" ON "mined_object" ("block_id") `)
        await db.query(`CREATE TABLE "mesh_topology" ("id" character varying NOT NULL, "faces" bytea NOT NULL, "face_count" integer NOT NULL, CONSTRAINT "PK_9069b0a7aa6abd0c3c022103e64" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "event" ("id" character varying NOT NULL, "index_in_block" integer NOT NULL, "phase" text NOT NULL, "pallet" text NOT NULL, "method" text NOT NULL, "args" jsonb, "block_id" character varying, "extrinsic_id" character varying, "call_id" character varying, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_event_block_26900bcf" ON "event" ("block_id") `)
        await db.query(`CREATE INDEX "idx_event_extrinsic_297167ec" ON "event" ("extrinsic_id") `)
        await db.query(`CREATE INDEX "idx_event_call_a1335fcb" ON "event" ("call_id") `)
        await db.query(`CREATE INDEX "idx_event_pallet_97942426" ON "event" ("pallet") `)
        await db.query(`CREATE INDEX "idx_event_method_ce4b1f83" ON "event" ("method") `)
        await db.query(`CREATE TABLE "call" ("id" character varying NOT NULL, "address" integer array NOT NULL, "pallet" text NOT NULL, "method" text NOT NULL, "args" jsonb, "success" boolean NOT NULL, "extrinsic_id" character varying, "block_id" character varying, "parent_id" character varying, "origin_id" character varying, CONSTRAINT "PK_2098af0169792a34f9cfdd39c47" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_call_extrinsic_83bd0b4e" ON "call" ("extrinsic_id") `)
        await db.query(`CREATE INDEX "idx_call_block_8f3ca806" ON "call" ("block_id") `)
        await db.query(`CREATE INDEX "idx_call_parent_d9400c51" ON "call" ("parent_id") `)
        await db.query(`CREATE INDEX "idx_call_pallet_7d7fb025" ON "call" ("pallet") `)
        await db.query(`CREATE INDEX "idx_call_method_235f10f9" ON "call" ("method") `)
        await db.query(`CREATE INDEX "idx_call_origin_6f603f05" ON "call" ("origin_id") `)
        await db.query(`CREATE TABLE "extrinsic" ("id" character varying NOT NULL, "index_in_block" integer NOT NULL, "hash" text NOT NULL, "pallet" text NOT NULL, "method" text NOT NULL, "success" boolean NOT NULL, "error" jsonb, "fee" numeric, "tip" numeric, "block_id" character varying, "signer_id" character varying, CONSTRAINT "PK_80d7db0e4b1e83e30336bc76755" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_extrinsic_block_bdb25d72" ON "extrinsic" ("block_id") `)
        await db.query(`CREATE INDEX "idx_extrinsic_hash_fb7b0484" ON "extrinsic" ("hash") `)
        await db.query(`CREATE INDEX "idx_extrinsic_pallet_10b2b37c" ON "extrinsic" ("pallet") `)
        await db.query(`CREATE INDEX "idx_extrinsic_method_9d338e4d" ON "extrinsic" ("method") `)
        await db.query(`CREATE INDEX "idx_extrinsic_signer_ad75509b" ON "extrinsic" ("signer_id") `)
        await db.query(`CREATE TABLE "evm_transaction" ("id" character varying NOT NULL, "tx_index" integer NOT NULL, "from" text NOT NULL, "to" text, "contract_address" text, "value" numeric NOT NULL, "input" bytea NOT NULL, "input_selector" text, "nonce" integer NOT NULL, "gas_limit" numeric NOT NULL, "gas_used" numeric NOT NULL, "gas_price" numeric NOT NULL, "tx_type" integer NOT NULL, "status" text NOT NULL, "status_reason" text, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "extrinsic_id" character varying, "block_id" character varying, CONSTRAINT "REL_20d8f952db57476b47a342828d" UNIQUE ("extrinsic_id"), CONSTRAINT "PK_5cb059f05ba72ac04ac1cfb3775" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_evm_transaction_extrinsic_9cdb2599" ON "evm_transaction" ("extrinsic_id") `)
        await db.query(`CREATE INDEX "idx_evm_transaction_block_4ee56ee5" ON "evm_transaction" ("block_id") `)
        await db.query(`CREATE INDEX "idx_evm_transaction_from_539e4b13" ON "evm_transaction" ("from") `)
        await db.query(`CREATE INDEX "idx_evm_transaction_to_ec297d22" ON "evm_transaction" ("to") `)
        await db.query(`CREATE INDEX "idx_evm_transaction_contract_address_cd30fa26" ON "evm_transaction" ("contract_address") `)
        await db.query(`CREATE INDEX "idx_evm_transaction_input_selector_1e46891d" ON "evm_transaction" ("input_selector") `)
        await db.query(`CREATE INDEX "idx_evm_transaction_timestamp_2aa7be18" ON "evm_transaction" ("timestamp") `)
        await db.query(`CREATE TABLE "evm_log" ("id" character varying NOT NULL, "log_index" integer NOT NULL, "address" text NOT NULL, "topic0" text, "topics" text array NOT NULL, "data" bytea NOT NULL, "transaction_id" character varying, "block_id" character varying, CONSTRAINT "PK_46aa4562a71db276862c5960c85" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_evm_log_transaction_aa2eff54" ON "evm_log" ("transaction_id") `)
        await db.query(`CREATE INDEX "idx_evm_log_block_c9cb892d" ON "evm_log" ("block_id") `)
        await db.query(`CREATE INDEX "idx_evm_log_topic0_7446ac04" ON "evm_log" ("topic0") `)
        await db.query(`CREATE INDEX "idx_evm_log_address_log_index_bd062870" ON "evm_log" ("address", "log_index") `)
        await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "name" text, "symbol" text, "decimals" integer, "total_supply" numeric NOT NULL, "holder_count" integer NOT NULL, "transfer_count" integer NOT NULL, "deploy_block" integer, "first_block" integer NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_token_symbol_0d3c74d6" ON "token" ("symbol") `)
        await db.query(`CREATE TABLE "token_transfer" ("id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "amount" numeric NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "token_id" character varying, "transaction_id" character varying, "block_id" character varying, CONSTRAINT "PK_77384b7f5874553f012eba9da41" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_token_transfer_token_e0bf4a8e" ON "token_transfer" ("token_id") `)
        await db.query(`CREATE INDEX "idx_token_transfer_from_13617e2f" ON "token_transfer" ("from") `)
        await db.query(`CREATE INDEX "idx_token_transfer_to_3543af45" ON "token_transfer" ("to") `)
        await db.query(`CREATE INDEX "idx_token_transfer_transaction_9b9a6656" ON "token_transfer" ("transaction_id") `)
        await db.query(`CREATE INDEX "idx_token_transfer_block_de0e3f3a" ON "token_transfer" ("block_id") `)
        await db.query(`CREATE INDEX "idx_token_transfer_timestamp_0bb3ae39" ON "token_transfer" ("timestamp") `)
        await db.query(`CREATE TABLE "token_holder" ("id" character varying NOT NULL, "address" text NOT NULL, "balance" numeric NOT NULL, "token_id" character varying, CONSTRAINT "PK_c5e10d5c2543fac00a5d3086a2c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_token_holder_address_766650f5" ON "token_holder" ("address") `)
        await db.query(`CREATE INDEX "idx_token_holder_token_balance_a93fa67e" ON "token_holder" ("token_id", "balance") `)
        await db.query(`CREATE TABLE "call_kind" ("id" character varying NOT NULL, "pallet" text NOT NULL, "method" text NOT NULL, CONSTRAINT "PK_01c5127f2a21a75c847bf6135c4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_call_kind_pallet_97f22f04" ON "call_kind" ("pallet") `)
        await db.query(`CREATE TABLE "registrar" ("id" character varying NOT NULL, "index" integer NOT NULL, "fee" numeric NOT NULL, "fields" numeric NOT NULL, "added_at" integer NOT NULL, "request_count" integer NOT NULL, "given_count" integer NOT NULL, "last_judgement_block" integer, "last_judgement_at" TIMESTAMP WITH TIME ZONE, "account_id" character varying, CONSTRAINT "PK_2d7bb9639e37cbd75296d2183b2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_registrar_index_bbf235ee" ON "registrar" ("index") `)
        await db.query(`CREATE INDEX "idx_registrar_account_c70e5df6" ON "registrar" ("account_id") `)
        await db.query(`CREATE TABLE "judgement" ("id" character varying NOT NULL, "kind" text, "fee" numeric, "block" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "registrar_id" character varying, "target_id" character varying, CONSTRAINT "PK_99667adcd9b4ba11ee00b59445d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_judgement_target_52d06aef" ON "judgement" ("target_id") `)
        await db.query(`CREATE INDEX "idx_judgement_block_e9143e28" ON "judgement" ("block") `)
        await db.query(`CREATE INDEX "idx_judgement_registrar_block_c7e4ceff" ON "judgement" ("registrar_id", "block") `)
        await db.query(`CREATE TABLE "track" ("id" character varying NOT NULL, "name" text NOT NULL, "max_deciding" integer NOT NULL, "max_spend" numeric NOT NULL, "decision_deposit" numeric NOT NULL, "prepare_period" integer NOT NULL, "decision_period" integer NOT NULL, "confirm_period" integer NOT NULL, "min_enactment_period" integer NOT NULL, "min_approval" jsonb NOT NULL, "min_support" jsonb NOT NULL, CONSTRAINT "PK_0631b9bcf521f8fab3a15f2c37e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "referendum" ("id" character varying NOT NULL, "index" integer NOT NULL, "origin" text, "proposal_hash" text, "title" text, "description" text, "proposal_call" text, "proposal_amount" numeric, "proposal_beneficiary" text, "proposal_bounty_index" integer, "submitted_at" integer NOT NULL, "status" character varying(10) NOT NULL, "deciding_since" integer, "confirming_since" integer, "ended_at" integer, "ayes" numeric NOT NULL, "nays" numeric NOT NULL, "support" numeric NOT NULL, "timeline" jsonb NOT NULL, "submission_depositor" text, "submission_deposit" numeric, "decision_depositor" text, "decision_deposit" numeric, "track_id" character varying, "submitter_id" character varying, CONSTRAINT "PK_772fc260f18c235a6327252ce00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_referendum_index_feec7826" ON "referendum" ("index") `)
        await db.query(`CREATE INDEX "idx_referendum_track_319f8fed" ON "referendum" ("track_id") `)
        await db.query(`CREATE INDEX "idx_referendum_proposal_bounty_index_d217b665" ON "referendum" ("proposal_bounty_index") `)
        await db.query(`CREATE INDEX "idx_referendum_submitter_3fca5094" ON "referendum" ("submitter_id") `)
        await db.query(`CREATE INDEX "idx_referendum_status_24792806" ON "referendum" ("status") `)
        await db.query(`CREATE INDEX "idx_referendum_submission_depositor_4bdb4f96" ON "referendum" ("submission_depositor") `)
        await db.query(`CREATE INDEX "idx_referendum_decision_depositor_a79f8b72" ON "referendum" ("decision_depositor") `)
        await db.query(`CREATE TABLE "vote" ("id" character varying NOT NULL, "decision" text NOT NULL, "amount" numeric NOT NULL, "conviction" text, "block" integer NOT NULL, "removed" boolean NOT NULL, "referendum_id" character varying, "voter_id" character varying, CONSTRAINT "PK_2d5932d46afe39c8176f9d4be72" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_vote_referendum_0f9860c6" ON "vote" ("referendum_id") `)
        await db.query(`CREATE INDEX "idx_vote_voter_f6a67bf9" ON "vote" ("voter_id") `)
        await db.query(`CREATE TABLE "delegation" ("id" character varying NOT NULL, "conviction" text NOT NULL, "balance" numeric NOT NULL, "block" integer NOT NULL, "who_id" character varying, "target_id" character varying, "track_id" character varying, CONSTRAINT "PK_a2cb6c9b942d68b109131beab44" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_delegation_who_4c79bac5" ON "delegation" ("who_id") `)
        await db.query(`CREATE INDEX "idx_delegation_target_54f285e6" ON "delegation" ("target_id") `)
        await db.query(`CREATE INDEX "idx_delegation_track_c05b90a8" ON "delegation" ("track_id") `)
        await db.query(`CREATE TABLE "treasury_spend" ("id" character varying NOT NULL, "kind" text NOT NULL, "amount" numeric NOT NULL, "status" text NOT NULL, "block" integer NOT NULL, "referendum_id" character varying, "beneficiary_id" character varying, CONSTRAINT "PK_8c06eb3f1cf0be0d565ef90ce69" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_treasury_spend_referendum_f3bdda66" ON "treasury_spend" ("referendum_id") `)
        await db.query(`CREATE INDEX "idx_treasury_spend_beneficiary_264a9618" ON "treasury_spend" ("beneficiary_id") `)
        await db.query(`CREATE INDEX "idx_treasury_spend_status_607b4e2e" ON "treasury_spend" ("status") `)
        await db.query(`CREATE TABLE "bounty" ("id" character varying NOT NULL, "index" integer NOT NULL, "value" numeric NOT NULL, "fee" numeric, "bond" numeric, "curator_deposit" numeric, "description" text, "status" text NOT NULL, "unlock_at" integer, "update_due" integer, "payout" numeric, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, "timeline" jsonb NOT NULL, "referendum_id" character varying, "proposer_id" character varying, "curator_id" character varying, "beneficiary_id" character varying, CONSTRAINT "PK_afc9754b790b0effd1d59257f4d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_bounty_index_1ff911c5" ON "bounty" ("index") `)
        await db.query(`CREATE INDEX "idx_bounty_referendum_dbb0dfcc" ON "bounty" ("referendum_id") `)
        await db.query(`CREATE INDEX "idx_bounty_proposer_d9eab326" ON "bounty" ("proposer_id") `)
        await db.query(`CREATE INDEX "idx_bounty_curator_33da2103" ON "bounty" ("curator_id") `)
        await db.query(`CREATE INDEX "idx_bounty_beneficiary_c5353b0f" ON "bounty" ("beneficiary_id") `)
        await db.query(`CREATE INDEX "idx_bounty_status_d57f0f1c" ON "bounty" ("status") `)
        await db.query(`CREATE INDEX "idx_bounty_updated_at_27303462" ON "bounty" ("updated_at") `)
        await db.query(`CREATE TABLE "child_bounty" ("id" character varying NOT NULL, "child_index" integer NOT NULL, "value" numeric NOT NULL, "fee" numeric, "curator_deposit" numeric, "description" text, "status" text NOT NULL, "payout" numeric, "created_at" integer NOT NULL, "updated_at" integer NOT NULL, "parent_id" character varying, "curator_id" character varying, "beneficiary_id" character varying, CONSTRAINT "PK_9f0ac2562a5e75dbd41a4a36eb9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_child_bounty_parent_8686a44b" ON "child_bounty" ("parent_id") `)
        await db.query(`CREATE INDEX "idx_child_bounty_curator_94b03874" ON "child_bounty" ("curator_id") `)
        await db.query(`CREATE INDEX "idx_child_bounty_beneficiary_8c6fab5d" ON "child_bounty" ("beneficiary_id") `)
        await db.query(`CREATE INDEX "idx_child_bounty_status_0b783feb" ON "child_bounty" ("status") `)
        await db.query(`CREATE TABLE "multisig_op" ("id" character varying NOT NULL, "call_hash" text NOT NULL, "deposit" numeric, "approvals" text array NOT NULL, "threshold" integer, "signatories" text array, "status" text NOT NULL, "result" text, "created_block" integer NOT NULL, "updated_block" integer NOT NULL, "multisig_id" character varying, "depositor_id" character varying, CONSTRAINT "PK_488d3b22602dffb203489a57cd1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_multisig_op_multisig_d1de6182" ON "multisig_op" ("multisig_id") `)
        await db.query(`CREATE INDEX "idx_multisig_op_call_hash_c150b6f4" ON "multisig_op" ("call_hash") `)
        await db.query(`CREATE INDEX "idx_multisig_op_depositor_95057224" ON "multisig_op" ("depositor_id") `)
        await db.query(`CREATE INDEX "idx_multisig_op_status_8aba75f3" ON "multisig_op" ("status") `)
        await db.query(`CREATE INDEX "idx_multisig_op_updated_block_f92f3020" ON "multisig_op" ("updated_block") `)
        await db.query(`CREATE TABLE "proxy_relation" ("id" character varying NOT NULL, "proxy_type" text NOT NULL, "delay" integer NOT NULL, "delegator_id" character varying, "delegatee_id" character varying, CONSTRAINT "PK_1e25c7a31ec3c79993008315a60" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_proxy_relation_delegator_e1a7bb3c" ON "proxy_relation" ("delegator_id") `)
        await db.query(`CREATE INDEX "idx_proxy_relation_delegatee_7ed4f938" ON "proxy_relation" ("delegatee_id") `)
        await db.query(`CREATE TABLE "prime_state" ("id" character varying NOT NULL, "since" integer NOT NULL, "account_id" character varying, CONSTRAINT "PK_806b5e47200d768221a9e26b77c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_prime_state_account_386e528c" ON "prime_state" ("account_id") `)
        await db.query(`CREATE TABLE "validator" ("id" character varying NOT NULL, "active" boolean NOT NULL, "locked_amount" numeric NOT NULL, "lock_expiry" integer, "offline_sessions" integer NOT NULL, "equivocations" integer NOT NULL, "kicked" text, "first_seen_block" integer NOT NULL, "last_active_session" integer NOT NULL, "account_id" character varying, CONSTRAINT "REL_4ddc35f6074f65fa2314a425a6" UNIQUE ("account_id"), CONSTRAINT "PK_ae0a943022c24bd60e7161e0fad" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_validator_account_6c60d32a" ON "validator" ("account_id") `)
        await db.query(`CREATE INDEX "idx_validator_active_c83c422c" ON "validator" ("active") `)
        await db.query(`CREATE TABLE "daily_stat" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "blocks" integer NOT NULL, "extrinsics_signed" integer NOT NULL, "transfers" integer NOT NULL, "transfer_volume" numeric NOT NULL, "evm_txs" integer NOT NULL, "fees" numeric NOT NULL, "ts_first" TIMESTAMP WITH TIME ZONE NOT NULL, "ts_last" TIMESTAMP WITH TIME ZONE NOT NULL, "difficulty_close" numeric NOT NULL, "issuance_total" numeric NOT NULL, "issuance_inactive" numeric NOT NULL, "treasury_pot" numeric NOT NULL, "cum_extrinsics_signed" numeric NOT NULL, "cum_transfers" numeric NOT NULL, "cum_transfer_volume" numeric NOT NULL, "accounts_total" integer NOT NULL, "referenda_total" integer NOT NULL, CONSTRAINT "PK_c2eb70552248e56c09515fb7744" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_stat_date_7855a7bd" ON "daily_stat" ("date") `)
        await db.query(`CREATE TABLE "miner_day_stat" ("id" character varying NOT NULL, "day" text NOT NULL, "blocks" integer NOT NULL, "rewards" numeric NOT NULL, "account_id" character varying, CONSTRAINT "PK_eb80260e642234974ff50f65a7d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_miner_day_stat_account_d8161b0b" ON "miner_day_stat" ("account_id") `)
        await db.query(`CREATE INDEX "idx_miner_day_stat_day_blocks_d35a091b" ON "miner_day_stat" ("day", "blocks") `)
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_id" character varying, "extrinsic_id" character varying, "call_id" character varying, "from_id" character varying, "to_id" character varying, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_transfer_block_1ca50110" ON "transfer" ("block_id") `)
        await db.query(`CREATE INDEX "idx_transfer_extrinsic_cd6f539e" ON "transfer" ("extrinsic_id") `)
        await db.query(`CREATE INDEX "idx_transfer_call_7739b9a5" ON "transfer" ("call_id") `)
        await db.query(`CREATE INDEX "idx_transfer_timestamp_cc1edef1" ON "transfer" ("timestamp") `)
        await db.query(`CREATE INDEX "idx_transfer_to_timestamp_7c7a109c" ON "transfer" ("to_id", "timestamp") `)
        await db.query(`CREATE INDEX "idx_transfer_from_timestamp_7990c96e" ON "transfer" ("from_id", "timestamp") `)
        await db.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_34645de9716c87ca55b53a9a049" FOREIGN KEY ("identity_super_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "block" ADD CONSTRAINT "FK_3ea8d7fe1c84ea1e9f25fbaf437" FOREIGN KEY ("author_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mined_object" ADD CONSTRAINT "FK_0aea185c9517d8774d2afacfe38" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_2b0d35d675c4f99751855c45021" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_129efedcb305c80256db2d57a59" FOREIGN KEY ("extrinsic_id") REFERENCES "extrinsic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_83cf1bd59aa4521ed882fa51452" FOREIGN KEY ("call_id") REFERENCES "call"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "call" ADD CONSTRAINT "FK_dde30e4f2c6a80f9236bfdf2590" FOREIGN KEY ("extrinsic_id") REFERENCES "extrinsic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "call" ADD CONSTRAINT "FK_bd3f11fd4110d60ac8b96cd62f3" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "call" ADD CONSTRAINT "FK_11c1e76d5be8f04c472c4a05b95" FOREIGN KEY ("parent_id") REFERENCES "call"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "call" ADD CONSTRAINT "FK_eab0ff9db79c8cc08db46adc05d" FOREIGN KEY ("origin_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "extrinsic" ADD CONSTRAINT "FK_a3b99daba1259dab0dd040d4f74" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "extrinsic" ADD CONSTRAINT "FK_886be421c92f221ac8234c6624c" FOREIGN KEY ("signer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "evm_transaction" ADD CONSTRAINT "FK_20d8f952db57476b47a342828d4" FOREIGN KEY ("extrinsic_id") REFERENCES "extrinsic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "evm_transaction" ADD CONSTRAINT "FK_9ee6a3ffcba2fecdf0b4a712e6b" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "evm_log" ADD CONSTRAINT "FK_277ad58012b98c0f1de0ca7e9ee" FOREIGN KEY ("transaction_id") REFERENCES "evm_transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "evm_log" ADD CONSTRAINT "FK_2bcbcb6f6681b1290ad7e51adad" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_transfer" ADD CONSTRAINT "FK_4dbddd00fdedf513899e70cc681" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_transfer" ADD CONSTRAINT "FK_b2bc7c264d1c698cd6147c6e1cd" FOREIGN KEY ("transaction_id") REFERENCES "evm_transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_transfer" ADD CONSTRAINT "FK_df880819edb0d6a3168fde64d71" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_holder" ADD CONSTRAINT "FK_fc70f9ab515920d249fa5e9a8ba" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "registrar" ADD CONSTRAINT "FK_468ca168db0480ba0354b8a3942" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "judgement" ADD CONSTRAINT "FK_fbfca402e42403ee3c68187e904" FOREIGN KEY ("registrar_id") REFERENCES "registrar"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "judgement" ADD CONSTRAINT "FK_4e1c4367e563d78edf1402a3ec7" FOREIGN KEY ("target_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "referendum" ADD CONSTRAINT "FK_678945daf4785b82db282ccce76" FOREIGN KEY ("track_id") REFERENCES "track"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "referendum" ADD CONSTRAINT "FK_a69a6309d62e9a87022d7dfbc66" FOREIGN KEY ("submitter_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "vote" ADD CONSTRAINT "FK_6c157f7819d8bf5869a9e2ab86a" FOREIGN KEY ("referendum_id") REFERENCES "referendum"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "vote" ADD CONSTRAINT "FK_f5c90d8438424ec0f044ef945a9" FOREIGN KEY ("voter_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_8fbb68f1262dfdbc59246d54316" FOREIGN KEY ("who_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_576dd01b7dbf4f888f9da184f20" FOREIGN KEY ("target_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "delegation" ADD CONSTRAINT "FK_b3387c663aa21e2ef130ada2180" FOREIGN KEY ("track_id") REFERENCES "track"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "treasury_spend" ADD CONSTRAINT "FK_b01bd2fa1f0336c4b06d0aaf31f" FOREIGN KEY ("referendum_id") REFERENCES "referendum"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "treasury_spend" ADD CONSTRAINT "FK_20804c0e2fda64a124094af2b36" FOREIGN KEY ("beneficiary_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bounty" ADD CONSTRAINT "FK_2344865614ac05d1080ff6f67f4" FOREIGN KEY ("referendum_id") REFERENCES "referendum"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bounty" ADD CONSTRAINT "FK_e94ac98c4983319111804bf57a3" FOREIGN KEY ("proposer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bounty" ADD CONSTRAINT "FK_81d35b2df3f7d7ecf605797bda8" FOREIGN KEY ("curator_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bounty" ADD CONSTRAINT "FK_f4f92297d9ae0fe553749b9a958" FOREIGN KEY ("beneficiary_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "child_bounty" ADD CONSTRAINT "FK_43dff5a0709210463cd0415b85b" FOREIGN KEY ("parent_id") REFERENCES "bounty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "child_bounty" ADD CONSTRAINT "FK_599fd61cec22a2a7b2041b98f0c" FOREIGN KEY ("curator_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "child_bounty" ADD CONSTRAINT "FK_1cd6f8fbbfe04f50dc9596def34" FOREIGN KEY ("beneficiary_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "multisig_op" ADD CONSTRAINT "FK_d9a6b54e9cbd141eea7bdf3ed40" FOREIGN KEY ("multisig_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "multisig_op" ADD CONSTRAINT "FK_8f5858db16dde3fffbd616c5050" FOREIGN KEY ("depositor_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "proxy_relation" ADD CONSTRAINT "FK_475b0bcb6aefee9f651b3f88ab3" FOREIGN KEY ("delegator_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "proxy_relation" ADD CONSTRAINT "FK_6d80e97f7778598dd914baa1d54" FOREIGN KEY ("delegatee_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "prime_state" ADD CONSTRAINT "FK_d4bc11b0f56e9b4654845c3f6f7" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "validator" ADD CONSTRAINT "FK_4ddc35f6074f65fa2314a425a6f" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "miner_day_stat" ADD CONSTRAINT "FK_74b6a61f949a388ff1c34be4f82" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_2699bb80b8c7c68d263fab954b0" FOREIGN KEY ("block_id") REFERENCES "block"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_06f5863364b6acc2e315ceba39a" FOREIGN KEY ("extrinsic_id") REFERENCES "extrinsic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_7fc8170b649010ce80aaa9bbbb2" FOREIGN KEY ("call_id") REFERENCES "call"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_7fc8170b649010ce80aaa9bbbb2"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_06f5863364b6acc2e315ceba39a"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_2699bb80b8c7c68d263fab954b0"`)
        await db.query(`ALTER TABLE "miner_day_stat" DROP CONSTRAINT "FK_74b6a61f949a388ff1c34be4f82"`)
        await db.query(`ALTER TABLE "validator" DROP CONSTRAINT "FK_4ddc35f6074f65fa2314a425a6f"`)
        await db.query(`ALTER TABLE "prime_state" DROP CONSTRAINT "FK_d4bc11b0f56e9b4654845c3f6f7"`)
        await db.query(`ALTER TABLE "proxy_relation" DROP CONSTRAINT "FK_6d80e97f7778598dd914baa1d54"`)
        await db.query(`ALTER TABLE "proxy_relation" DROP CONSTRAINT "FK_475b0bcb6aefee9f651b3f88ab3"`)
        await db.query(`ALTER TABLE "multisig_op" DROP CONSTRAINT "FK_8f5858db16dde3fffbd616c5050"`)
        await db.query(`ALTER TABLE "multisig_op" DROP CONSTRAINT "FK_d9a6b54e9cbd141eea7bdf3ed40"`)
        await db.query(`ALTER TABLE "child_bounty" DROP CONSTRAINT "FK_1cd6f8fbbfe04f50dc9596def34"`)
        await db.query(`ALTER TABLE "child_bounty" DROP CONSTRAINT "FK_599fd61cec22a2a7b2041b98f0c"`)
        await db.query(`ALTER TABLE "child_bounty" DROP CONSTRAINT "FK_43dff5a0709210463cd0415b85b"`)
        await db.query(`ALTER TABLE "bounty" DROP CONSTRAINT "FK_f4f92297d9ae0fe553749b9a958"`)
        await db.query(`ALTER TABLE "bounty" DROP CONSTRAINT "FK_81d35b2df3f7d7ecf605797bda8"`)
        await db.query(`ALTER TABLE "bounty" DROP CONSTRAINT "FK_e94ac98c4983319111804bf57a3"`)
        await db.query(`ALTER TABLE "bounty" DROP CONSTRAINT "FK_2344865614ac05d1080ff6f67f4"`)
        await db.query(`ALTER TABLE "treasury_spend" DROP CONSTRAINT "FK_20804c0e2fda64a124094af2b36"`)
        await db.query(`ALTER TABLE "treasury_spend" DROP CONSTRAINT "FK_b01bd2fa1f0336c4b06d0aaf31f"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_b3387c663aa21e2ef130ada2180"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_576dd01b7dbf4f888f9da184f20"`)
        await db.query(`ALTER TABLE "delegation" DROP CONSTRAINT "FK_8fbb68f1262dfdbc59246d54316"`)
        await db.query(`ALTER TABLE "vote" DROP CONSTRAINT "FK_f5c90d8438424ec0f044ef945a9"`)
        await db.query(`ALTER TABLE "vote" DROP CONSTRAINT "FK_6c157f7819d8bf5869a9e2ab86a"`)
        await db.query(`ALTER TABLE "referendum" DROP CONSTRAINT "FK_a69a6309d62e9a87022d7dfbc66"`)
        await db.query(`ALTER TABLE "referendum" DROP CONSTRAINT "FK_678945daf4785b82db282ccce76"`)
        await db.query(`ALTER TABLE "judgement" DROP CONSTRAINT "FK_4e1c4367e563d78edf1402a3ec7"`)
        await db.query(`ALTER TABLE "judgement" DROP CONSTRAINT "FK_fbfca402e42403ee3c68187e904"`)
        await db.query(`ALTER TABLE "registrar" DROP CONSTRAINT "FK_468ca168db0480ba0354b8a3942"`)
        await db.query(`ALTER TABLE "token_holder" DROP CONSTRAINT "FK_fc70f9ab515920d249fa5e9a8ba"`)
        await db.query(`ALTER TABLE "token_transfer" DROP CONSTRAINT "FK_df880819edb0d6a3168fde64d71"`)
        await db.query(`ALTER TABLE "token_transfer" DROP CONSTRAINT "FK_b2bc7c264d1c698cd6147c6e1cd"`)
        await db.query(`ALTER TABLE "token_transfer" DROP CONSTRAINT "FK_4dbddd00fdedf513899e70cc681"`)
        await db.query(`ALTER TABLE "evm_log" DROP CONSTRAINT "FK_2bcbcb6f6681b1290ad7e51adad"`)
        await db.query(`ALTER TABLE "evm_log" DROP CONSTRAINT "FK_277ad58012b98c0f1de0ca7e9ee"`)
        await db.query(`ALTER TABLE "evm_transaction" DROP CONSTRAINT "FK_9ee6a3ffcba2fecdf0b4a712e6b"`)
        await db.query(`ALTER TABLE "evm_transaction" DROP CONSTRAINT "FK_20d8f952db57476b47a342828d4"`)
        await db.query(`ALTER TABLE "extrinsic" DROP CONSTRAINT "FK_886be421c92f221ac8234c6624c"`)
        await db.query(`ALTER TABLE "extrinsic" DROP CONSTRAINT "FK_a3b99daba1259dab0dd040d4f74"`)
        await db.query(`ALTER TABLE "call" DROP CONSTRAINT "FK_eab0ff9db79c8cc08db46adc05d"`)
        await db.query(`ALTER TABLE "call" DROP CONSTRAINT "FK_11c1e76d5be8f04c472c4a05b95"`)
        await db.query(`ALTER TABLE "call" DROP CONSTRAINT "FK_bd3f11fd4110d60ac8b96cd62f3"`)
        await db.query(`ALTER TABLE "call" DROP CONSTRAINT "FK_dde30e4f2c6a80f9236bfdf2590"`)
        await db.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_83cf1bd59aa4521ed882fa51452"`)
        await db.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_129efedcb305c80256db2d57a59"`)
        await db.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_2b0d35d675c4f99751855c45021"`)
        await db.query(`ALTER TABLE "mined_object" DROP CONSTRAINT "FK_0aea185c9517d8774d2afacfe38"`)
        await db.query(`ALTER TABLE "block" DROP CONSTRAINT "FK_3ea8d7fe1c84ea1e9f25fbaf437"`)
        await db.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_34645de9716c87ca55b53a9a049"`)
        await db.query(`DROP INDEX "public"."idx_transfer_from_timestamp_7990c96e"`)
        await db.query(`DROP INDEX "public"."idx_transfer_to_timestamp_7c7a109c"`)
        await db.query(`DROP INDEX "public"."idx_transfer_timestamp_cc1edef1"`)
        await db.query(`DROP INDEX "public"."idx_transfer_call_7739b9a5"`)
        await db.query(`DROP INDEX "public"."idx_transfer_extrinsic_cd6f539e"`)
        await db.query(`DROP INDEX "public"."idx_transfer_block_1ca50110"`)
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "public"."idx_miner_day_stat_day_blocks_d35a091b"`)
        await db.query(`DROP INDEX "public"."idx_miner_day_stat_account_d8161b0b"`)
        await db.query(`DROP TABLE "miner_day_stat"`)
        await db.query(`DROP INDEX "public"."idx_daily_stat_date_7855a7bd"`)
        await db.query(`DROP TABLE "daily_stat"`)
        await db.query(`DROP INDEX "public"."idx_validator_active_c83c422c"`)
        await db.query(`DROP INDEX "public"."idx_validator_account_6c60d32a"`)
        await db.query(`DROP TABLE "validator"`)
        await db.query(`DROP INDEX "public"."idx_prime_state_account_386e528c"`)
        await db.query(`DROP TABLE "prime_state"`)
        await db.query(`DROP INDEX "public"."idx_proxy_relation_delegatee_7ed4f938"`)
        await db.query(`DROP INDEX "public"."idx_proxy_relation_delegator_e1a7bb3c"`)
        await db.query(`DROP TABLE "proxy_relation"`)
        await db.query(`DROP INDEX "public"."idx_multisig_op_updated_block_f92f3020"`)
        await db.query(`DROP INDEX "public"."idx_multisig_op_status_8aba75f3"`)
        await db.query(`DROP INDEX "public"."idx_multisig_op_depositor_95057224"`)
        await db.query(`DROP INDEX "public"."idx_multisig_op_call_hash_c150b6f4"`)
        await db.query(`DROP INDEX "public"."idx_multisig_op_multisig_d1de6182"`)
        await db.query(`DROP TABLE "multisig_op"`)
        await db.query(`DROP INDEX "public"."idx_child_bounty_status_0b783feb"`)
        await db.query(`DROP INDEX "public"."idx_child_bounty_beneficiary_8c6fab5d"`)
        await db.query(`DROP INDEX "public"."idx_child_bounty_curator_94b03874"`)
        await db.query(`DROP INDEX "public"."idx_child_bounty_parent_8686a44b"`)
        await db.query(`DROP TABLE "child_bounty"`)
        await db.query(`DROP INDEX "public"."idx_bounty_updated_at_27303462"`)
        await db.query(`DROP INDEX "public"."idx_bounty_status_d57f0f1c"`)
        await db.query(`DROP INDEX "public"."idx_bounty_beneficiary_c5353b0f"`)
        await db.query(`DROP INDEX "public"."idx_bounty_curator_33da2103"`)
        await db.query(`DROP INDEX "public"."idx_bounty_proposer_d9eab326"`)
        await db.query(`DROP INDEX "public"."idx_bounty_referendum_dbb0dfcc"`)
        await db.query(`DROP INDEX "public"."idx_bounty_index_1ff911c5"`)
        await db.query(`DROP TABLE "bounty"`)
        await db.query(`DROP INDEX "public"."idx_treasury_spend_status_607b4e2e"`)
        await db.query(`DROP INDEX "public"."idx_treasury_spend_beneficiary_264a9618"`)
        await db.query(`DROP INDEX "public"."idx_treasury_spend_referendum_f3bdda66"`)
        await db.query(`DROP TABLE "treasury_spend"`)
        await db.query(`DROP INDEX "public"."idx_delegation_track_c05b90a8"`)
        await db.query(`DROP INDEX "public"."idx_delegation_target_54f285e6"`)
        await db.query(`DROP INDEX "public"."idx_delegation_who_4c79bac5"`)
        await db.query(`DROP TABLE "delegation"`)
        await db.query(`DROP INDEX "public"."idx_vote_voter_f6a67bf9"`)
        await db.query(`DROP INDEX "public"."idx_vote_referendum_0f9860c6"`)
        await db.query(`DROP TABLE "vote"`)
        await db.query(`DROP INDEX "public"."idx_referendum_decision_depositor_a79f8b72"`)
        await db.query(`DROP INDEX "public"."idx_referendum_submission_depositor_4bdb4f96"`)
        await db.query(`DROP INDEX "public"."idx_referendum_status_24792806"`)
        await db.query(`DROP INDEX "public"."idx_referendum_submitter_3fca5094"`)
        await db.query(`DROP INDEX "public"."idx_referendum_proposal_bounty_index_d217b665"`)
        await db.query(`DROP INDEX "public"."idx_referendum_track_319f8fed"`)
        await db.query(`DROP INDEX "public"."idx_referendum_index_feec7826"`)
        await db.query(`DROP TABLE "referendum"`)
        await db.query(`DROP TABLE "track"`)
        await db.query(`DROP INDEX "public"."idx_judgement_registrar_block_c7e4ceff"`)
        await db.query(`DROP INDEX "public"."idx_judgement_block_e9143e28"`)
        await db.query(`DROP INDEX "public"."idx_judgement_target_52d06aef"`)
        await db.query(`DROP TABLE "judgement"`)
        await db.query(`DROP INDEX "public"."idx_registrar_account_c70e5df6"`)
        await db.query(`DROP INDEX "public"."idx_registrar_index_bbf235ee"`)
        await db.query(`DROP TABLE "registrar"`)
        await db.query(`DROP INDEX "public"."idx_call_kind_pallet_97f22f04"`)
        await db.query(`DROP TABLE "call_kind"`)
        await db.query(`DROP INDEX "public"."idx_token_holder_token_balance_a93fa67e"`)
        await db.query(`DROP INDEX "public"."idx_token_holder_address_766650f5"`)
        await db.query(`DROP TABLE "token_holder"`)
        await db.query(`DROP INDEX "public"."idx_token_transfer_timestamp_0bb3ae39"`)
        await db.query(`DROP INDEX "public"."idx_token_transfer_block_de0e3f3a"`)
        await db.query(`DROP INDEX "public"."idx_token_transfer_transaction_9b9a6656"`)
        await db.query(`DROP INDEX "public"."idx_token_transfer_to_3543af45"`)
        await db.query(`DROP INDEX "public"."idx_token_transfer_from_13617e2f"`)
        await db.query(`DROP INDEX "public"."idx_token_transfer_token_e0bf4a8e"`)
        await db.query(`DROP TABLE "token_transfer"`)
        await db.query(`DROP INDEX "public"."idx_token_symbol_0d3c74d6"`)
        await db.query(`DROP TABLE "token"`)
        await db.query(`DROP INDEX "public"."idx_evm_log_address_log_index_bd062870"`)
        await db.query(`DROP INDEX "public"."idx_evm_log_topic0_7446ac04"`)
        await db.query(`DROP INDEX "public"."idx_evm_log_block_c9cb892d"`)
        await db.query(`DROP INDEX "public"."idx_evm_log_transaction_aa2eff54"`)
        await db.query(`DROP TABLE "evm_log"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_timestamp_2aa7be18"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_input_selector_1e46891d"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_contract_address_cd30fa26"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_to_ec297d22"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_from_539e4b13"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_block_4ee56ee5"`)
        await db.query(`DROP INDEX "public"."idx_evm_transaction_extrinsic_9cdb2599"`)
        await db.query(`DROP TABLE "evm_transaction"`)
        await db.query(`DROP INDEX "public"."idx_extrinsic_signer_ad75509b"`)
        await db.query(`DROP INDEX "public"."idx_extrinsic_method_9d338e4d"`)
        await db.query(`DROP INDEX "public"."idx_extrinsic_pallet_10b2b37c"`)
        await db.query(`DROP INDEX "public"."idx_extrinsic_hash_fb7b0484"`)
        await db.query(`DROP INDEX "public"."idx_extrinsic_block_bdb25d72"`)
        await db.query(`DROP TABLE "extrinsic"`)
        await db.query(`DROP INDEX "public"."idx_call_origin_6f603f05"`)
        await db.query(`DROP INDEX "public"."idx_call_method_235f10f9"`)
        await db.query(`DROP INDEX "public"."idx_call_pallet_7d7fb025"`)
        await db.query(`DROP INDEX "public"."idx_call_parent_d9400c51"`)
        await db.query(`DROP INDEX "public"."idx_call_block_8f3ca806"`)
        await db.query(`DROP INDEX "public"."idx_call_extrinsic_83bd0b4e"`)
        await db.query(`DROP TABLE "call"`)
        await db.query(`DROP INDEX "public"."idx_event_method_ce4b1f83"`)
        await db.query(`DROP INDEX "public"."idx_event_pallet_97942426"`)
        await db.query(`DROP INDEX "public"."idx_event_call_a1335fcb"`)
        await db.query(`DROP INDEX "public"."idx_event_extrinsic_297167ec"`)
        await db.query(`DROP INDEX "public"."idx_event_block_26900bcf"`)
        await db.query(`DROP TABLE "event"`)
        await db.query(`DROP TABLE "mesh_topology"`)
        await db.query(`DROP INDEX "public"."idx_mined_object_block_a24f655d"`)
        await db.query(`DROP TABLE "mined_object"`)
        await db.query(`DROP TABLE "chain_info"`)
        await db.query(`DROP INDEX "public"."idx_block_finalized_b535c2b5"`)
        await db.query(`DROP INDEX "public"."idx_block_author_c116954b"`)
        await db.query(`DROP INDEX "public"."idx_block_timestamp_82806c7c"`)
        await db.query(`DROP INDEX "public"."idx_block_hash_b194b635"`)
        await db.query(`DROP INDEX "public"."idx_block_height_b20720ad"`)
        await db.query(`DROP TABLE "block"`)
        await db.query(`DROP INDEX "public"."idx_account_evm_address_66f5172b"`)
        await db.query(`DROP INDEX "public"."idx_account_username_e1e37d55"`)
        await db.query(`DROP INDEX "public"."idx_account_identity_super_6eb9fc9a"`)
        await db.query(`DROP INDEX "public"."idx_account_identity_status_8b941a81"`)
        await db.query(`DROP INDEX "public"."idx_account_identity_display_842c1051"`)
        await db.query(`DROP INDEX "public"."idx_account_last_active_block_82d33d5a"`)
        await db.query(`DROP TABLE "account"`)
    }
}
